In [12]:
pip install pandas==1.5.3

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 67.5 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.1.1
    Uninstalling pandas-2.1.1:
      Successfully uninstalled pandas-2.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyldavis 3.4.1 requires pandas>=2.0.0, but you have pandas 1.5.3 which is incompatible.


In [2]:
pip install pyLDAvis

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 32.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 66.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 29.2 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.1.1 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.26.0 which is incompatible.
tensorflow 2.13.0 

In [ ]:
# pip install pandas==1.5.3
# pip install pyLDAvis

In [61]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tashaphyne.stemming import ArabicLightStemmer
from gensim.utils import simple_preprocess
from gensim import models, matutils
from gensim.corpora import Dictionary
from gensim.models import CoherenceModel
import pyLDAvis
import pyLDAvis.gensim

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [62]:
df = pd.read_csv('/content/document_dataset (1) (1).csv')

nltk.download('stopwords')
arabic_stop_words = set(stopwords.words('arabic'))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [63]:
def select_class(the_label):
    global class_selected
    class_selected = df[df[the_label] == 1]
    return class_selected


def list_text(text_to_list):
    list_name = []
    for i in range(0, len(text_to_list)):
        extracted_text = text_to_list.iloc[i, 3]
        list_name.append(extracted_text)
    return list_name


def show_stopwords():
    return arabic_stop_words


def tokenize_stemming_stopwords(the_text):
    tokenized_text = simple_preprocess(the_text)
    filtered_tokens = [token for token in tokenized_text if token not in arabic_stop_words]
    stemmer = ArabicLightStemmer()
    ready_text = [stemmer.light_stem(word) for word in filtered_tokens]
    return ready_text


def apply_tf_idf(text_list):
    global corpus, id2word
    vectorizer = TfidfVectorizer()
    tfidf = vectorizer.fit_transform(text_list)
    id2word = {v: k for k, v in vectorizer.vocabulary_.items()}
    corpus = matutils.Sparse2Corpus(tfidf, documents_columns=False)
    id2word = Dictionary.from_corpus(corpus, id2word=id2word)
    return tfidf

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


id                                 title                        author  \
0  13                         لساناً عربيا                 مناضل حسين علي   
1  42  خروج الوهابية على الخلافة العثمانية    قراءة تاريخية ومناقشة شرعية   
2  72    القول المفيد في أحكام صيام العبيد                       ياسر علي   
3  78                           حكم ووصايا      الشيخ عبد القادر الجيلاني   
4  63  الحركة الوهابية صنيعة الأيدي الخفية                  عبد الله عكور   

                                                data  Class 199  Class 22  \
0  1 2 3 ﺦﺧ ػﺭ٤ﺥ ﺥ ﻙ٤ ػ٢ ـ 1 4 ﺍﻼﻫﺩﺍﺀ ﻼﯨ ﺹﺎﺤﺑ ﻻﺮﺳ...          0         0   
1  ﻳﺎﺳﻴﻦ ﺑﻦ ﻋﻠﻲ �� �� ﺧﺮﻭﺝ ﺍﻟﻮﻫﺎﺑﻴﺔ ﺧﺮﻭﺝ ﺍﻟﻮﻫﺎﺑﻴﺔ...          1         0   
2  ﺎﻤﻠﻔﻳﺩ ﻼﻗﻮﻟ ﻲﻓ ﻼﻌﺒﻳﺩ ﺺﻳﺎﻣ ﺄﺤﻛﺎﻣ ))ﺢﺒﺛ ﻢﻔﻳﺩ ﺞﻴﻤ...          0         0   
3  -١ - – – -2 -  ﺎﻤﻟﻭﺎﺼﻓﺎﺗ ﻼﻔﻨﻳﺓ ﺡ ﻡ ﻭﻮﺻﺎﻳﺎﻣﻭﻭﻭ...          1         0   
4  ﺲﻠﺴﻟﺓ ﻚﺸﻓ ﺢﻘﻴﻗﺓ ﻻﻮﻫﺎﺒﻳﺓ )7( ﺎﺤﻟﺮﻛﺓ ﻻﻮﻫﺎﺒﻳﺓ ﻱﺪﻳ...          1         0   

   Class 252  Class 303  Class 326  Class 34  Class 366  Class 422  Class 461  \
0          0          0          0         0          0          0          0   
1          0          0          0         0          1          0          0   
2          0          0          0         0          0          0          0   
3          0          0          0         0          0          0          0   
4          0          0          0         0          1          1          0   

   Class 467  Class 69  Class 83  
0          1         0         0  
1          0         0         1  
2          0         0         1  
3          0         0         1  
4          0         0         0

In [57]:
class_30 = select_class("Class 326")
class30_list = list_text(class_30)
final_text = tokenize_stemming_stopwords(class30_list[5])
class30_tfidf = apply_tf_idf(final_text)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [41]:
print(class30_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [59]:
model_lda = models.LdaModel(corpus=corpus, num_topics=2, id2word=id2word, passes=20)
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(model_lda, corpus, id2word, mds='mmds', R=10)
vis

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/sklearn/manifold/_mds.py:299: FutureWarning: The default value of `normalized_stress` will change to `'auto'` in version 1.4. To suppress this warning, manually set the value of `normalized_stress`.
  warnings.warn(


PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
1     -0.009076 -0.160172       1        1  50.271284
0      0.009076  0.160172       2        1  49.728716, topic_info=         Term        Freq       Total Category  logprob  loglift
6       ﺍﳊﺮﻳﺔ  110.000000  110.000000  Default  10.0000  10.0000
25         ﻣﻦ   50.000000   50.000000  Default   9.0000   9.0000
54       ﺣﺮﻳﺔ   38.000000   38.000000  Default   8.0000   8.0000
238        ﻫﻲ   33.000000   33.000000  Default   7.0000   7.0000
102        ﺃﻥ   32.000000   32.000000  Default   6.0000   6.0000
239        ﺍﷲ   30.000000   30.000000  Default   5.0000   5.0000
91     ﺍﻹﻧﺴﺎﻥ   29.000000   29.000000  Default   4.0000   4.0000
351     ﺍﻟﻌﺎﱂ   28.000000   28.000000  Default   3.0000   3.0000
124       ﻋﻠﻰ   27.000000   27.000000  Default   2.0000   2.0000
49        ﻫﺬﺍ   21.000000   21.000000  Default   1.0000   1.0000
6       ﺍﳊﺮﻳﺔ  110.546742  110.891758   Topic1  -2.5692   0.6846
25         ﻣﻦ   50.000133   50.345667   Topic1  -3.3627   0.6808
54       ﺣﺮﻳﺔ   37.923939   38.268646   Topic1  -3.6391   0.6787
238        ﻫﻲ   33.587432   33.933249   Topic1  -3.7605   0.6775
102        ﺃﻥ   32.207160   32.552619   Topic1  -3.8025   0.6771
239        ﺍﷲ   29.811215   30.157668   Topic1  -3.8798   0.6762
124       ﻋﻠﻰ   27.104336   27.449225   Topic1  -3.9750   0.6751
209        ﻫﻮ   19.062133   19.408526   Topic1  -4.3270   0.6697
70        ﺍﻟﱵ   16.792119   17.136901   Topic1  -4.4538   0.6674
235       ﻟﻴﺲ   14.886204   15.231516   Topic1  -4.5742   0.6648
91     ﺍﻹﻧﺴﺎﻥ   29.312054   29.705697   Topic2  -3.8858   0.6852
351     ﺍﻟﻌﺎﱂ   28.320841   28.717668   Topic2  -3.9202   0.6847
49        ﻫﺬﺍ   20.994154   21.388211   Topic2  -4.2196   0.6800
53         ﻋﻦ   18.093028   18.487160   Topic2  -4.3683   0.6770
234       ﻟﻜﻦ   17.259568   17.653874   Topic2  -4.4155   0.6760
30         ﺇﱃ   14.421058   14.814778   Topic2  -4.5951   0.6717
1020    ﺍﻟﻌﺪﻡ   13.891865   14.290045   Topic2  -4.6325   0.6703
58         ﻣﺎ   13.556553   13.950484   Topic2  -4.6570   0.6699
266   ﺍﻟﺜﺎﻧﻴﺔ   12.306409   12.700550   Topic2  -4.7537   0.6671
282      ﻟﻴﺴﺖ   11.873493   12.268479   Topic2  -4.7895   0.6659, token_table=      Topic      Freq     Term
term                          
102       1  0.983024       ﺃﻥ
30        2  0.945002       ﺇﱃ
6         1  1.000976    ﺍﳊﺮﻳﺔ
239       1  0.994772       ﺍﷲ
70        1  0.992011      ﺍﻟﱵ
266       2  0.944841  ﺍﻟﺜﺎﻧﻴﺔ
351       2  0.975010    ﺍﻟﻌﺎﱂ
1020      2  0.979703    ﺍﻟﻌﺪﻡ
91        2  0.976244   ﺍﻹﻧﺴﺎﻥ
54        1  0.992980     ﺣﺮﻳﺔ
124       1  0.983634      ﻋﻠﻰ
53        2  0.973649       ﻋﻦ
234       2  0.962961      ﻟﻜﻦ
235       1  0.984800      ﻟﻴﺲ
282       2  0.978116     ﻟﻴﺴﺖ
58        2  1.003549       ﻣﺎ
25        1  0.993134       ﻣﻦ
49        2  0.981849      ﻫﺬﺍ
209       1  0.978951       ﻫﻮ
238       1  1.001967       ﻫﻲ, R=10, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[2, 1])